name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]  # Defining the OS matrix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.5'  # Set Go version 1.23.5

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...  # Adjust build command as needed

      - name: Run tests
        run: go test ./...  # Optional: run tests
